In [56]:
import sklearn.datasets as skd
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from sklearn import metrics
from sklearn.metrics import accuracy_score
import numpy as np

In [57]:
categories = ['alt.atheism', 'soc.religion.christian','comp.graphics', 'sci.med']
news_train = skd.load_files('C:/Personal/TextClass/Fetch20News/Train', categories= categories, encoding= 'ISO-8859-1')
news_test = skd.load_files('C:/Personal/TextClass/Fetch20News/test/',categories= categories, encoding= 'ISO-8859-1')

In [58]:
print(news_train.keys())
print(news_test.keys())

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])
dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])


In [59]:
print(news_train.target_names)

['alt.atheism', 'comp.graphics', 'sci.med', 'soc.religion.christian']


In [60]:
print(news_train.target)

[2 1 3 ... 1 1 2]


__Demon Code for Understanding of countvectorizer__

__Term Frequency__: How often a given words appear in a document.

__Inverse Frequency Document__: Create weights for every document based on the count. This downscales the words that appear a lot accorss documents. 

In [61]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

text = ["The quick brown fox jumped over the lazy dog.",
    "The dog.",
     "The fox,"   
]
vector = CountVectorizer()
vector.fit(text)
#print vocabulary
print("Vocabulary: ",vector.vocabulary_)
print("Feature Name: ",vector.get_feature_names())

counts = vector.transform(text)

print("The shape : ",counts.shape)
print(counts.toarray())

vectorizer = TfidfTransformer()
vectorizer.fit(counts)

print("Learning Frequency for all feature: ", str(vectorizer.idf_))
freq = vectorizer.transform(counts)
freq.toarray()

Vocabulary:  {'the': 7, 'quick': 6, 'brown': 0, 'fox': 2, 'jumped': 3, 'over': 5, 'lazy': 4, 'dog': 1}
Feature Name:  ['brown', 'dog', 'fox', 'jumped', 'lazy', 'over', 'quick', 'the']
The shape :  (3, 8)
[[1 1 1 1 1 1 1 2]
 [0 1 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 1]]
Learning Frequency for all feature:  [1.69314718 1.28768207 1.28768207 1.69314718 1.69314718 1.69314718
 1.69314718 1.        ]


array([[0.36388646, 0.27674503, 0.27674503, 0.36388646, 0.36388646,
        0.36388646, 0.36388646, 0.42983441],
       [0.        , 0.78980693, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.61335554],
       [0.        , 0.        , 0.78980693, 0.        , 0.        ,
        0.        , 0.        , 0.61335554]])

__Demo Code End__

In [62]:
#Create Term Frequency (TF)
count_vector = CountVectorizer()
x_train_tf = count_vector.fit_transform(news_train.data)
x_train_tf.shape

(2257, 35788)

In [63]:
#Create Inverse Frequency Document (TFIDF)
Tfidf_Vectorizer = TfidfTransformer()
x_train_tfidf = Tfidf_Vectorizer.fit_transform(x_train_tf)
x_train_tfidf.shape

(2257, 35788)

In [72]:
cf = MultinomialNB().fit(x_train_tfidf,news_train.target)



In [75]:
count_vector = CountVectorizer()
x_test_tf = count_vector.fit_transform(news_test.data)
Tfidf_Vectorizer = TfidfTransformer()
x_test_tfidf = Tfidf_Vectorizer.fit_transform(x_test_tf)
x_test_tfidf.shape

(1502, 30786)

In [77]:
# predicted= cf.predict(x_test_tfidf)

text_clf = Pipeline([('vect', TfidfVectorizer()), 
                      ('clf', MultinomialNB()) ])

# train the model
text_clf.fit(news_train.data, news_train.target)
# Predict the test cases
predicted = text_clf.predict(news_test.data)

In [78]:
print('Accuracy achieved is ' + str(np.mean(predicted == news_test.target)))
print(metrics.classification_report(news_test.target, predicted, target_names=news_test.target_names)),
metrics.confusion_matrix(news_test.target, predicted)


Accuracy achieved is 0.8348868175765646
                        precision    recall  f1-score   support

           alt.atheism       0.97      0.60      0.74       319
         comp.graphics       0.96      0.89      0.92       389
               sci.med       0.97      0.81      0.88       396
soc.religion.christian       0.65      0.99      0.78       398

             micro avg       0.83      0.83      0.83      1502
             macro avg       0.89      0.82      0.83      1502
          weighted avg       0.88      0.83      0.84      1502



array([[192,   2,   6, 119],
       [  2, 347,   4,  36],
       [  2,  11, 322,  61],
       [  2,   2,   1, 393]], dtype=int64)